[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 8080
# Disable auto-reload of the web app.
# For some reason the injected code breaks our injected scripts
no_autoreload = true

[[hooks]]
stage = "post_build"
command = "./build_for_kaios25.sh"
